apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gen-sa-token
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gen-sa-token
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                 name: oc-command-pod
                 namespace: aap-runner
                spec:
                 serviceAccountName: oc-runner
                 containers:
                   - name: oc
                     image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
                     command: ["/bin/bash", "-c"]
                     args:
                       - |
                         echo "Checking if token already exists";
                         oc get secret aap-sa-token &> /dev/null
                         if [ $? -eq 0 ]; then
                           echo "Secret aap-sa-token exists, exiting."
                           exit 1
                         else
                           echo "Secret aap-sa-token does not exist, creating."
                         fi
                         echo "Creating sa token";
                         TOKEN=$(oc create token aap-sa --duration=$((365*24))h);
                         echo "Create secret from token";
                         oc create secret generic aap-sa-token --from-literal=token=$TOKEN
                 restartPolicy: Never
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-gen-sa-token
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/aap-cg'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-gen-sa-token
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-gen-sa-token
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-gen-sa-token
    apiGroup: policy.open-cluster-management.io
    kind: Policy
