apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-aap-cert-bundle
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes MetalLB Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  dependencies:
    - name: policy-aap-instance
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-cert-bundle #figure this out
          namespace: policies-autoshift
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ .Values.aap.cabundleName }}
                  namespace: {{ .Values.aap.namespace }}
                type: Opaque
                data:
                  trusted-ca-bundle: {{ "{{" }} (lookup "v1" "ConfigMap" "policies-autoshift" "basic-config-map") {{ "}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-aap-cert-bundle
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/aap'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-aap-cert-bundle
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-aap-cert-bundle
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-aap-cert-bundle
    apiGroup: policy.open-cluster-management.io
    kind: Policy